server.port=38080

server.ssl.enabled=true
server.ssl.key-store=file:/home/studs/s367785/services/navigator-services-dir/server.jks
server.ssl.key-store-password=changeit
server.ssl.key-store-type=JKS
server.ssl.key-alias=tomcat

eureka.client.serviceUrl.defaultZone=https://localhost:${server.port}/eureka

netflix.metrics.servo.enabled=false

server.tomcat.max-threads=10
server.tomcat.min-spare-threads=2

