server.port=38090

server.servlet.context-path=/

server.ssl.enabled=true
server.ssl.key-store=file:/home/studs/s367785/services/navigator-services-dir/server.jks
server.ssl.key-store-password=changeit
server.ssl.key-store-type=JKS
server.ssl.key-alias=tomcat

eureka.client.service-url.defaultZone=https://localhost:38080/eureka
eureka.instance.lease-renewal-interval-in-seconds=60
eureka.instance.lease-expiration-duration-in-seconds=180

route-management.base-url=https://localhost:38443/route-management-service

spring.mvc.cors.enabled=true

server.tomcat.max-threads=10
server.tomcat.min-spare-threads=2

netflix.metrics.servo.enabled=false

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE