server.port=38080

server.ssl.enabled=true
server.ssl.key-store=file:/home/studs/s367785/services/navigator-services-dir/server.jks
server.ssl.key-store-password=changeit
server.ssl.key-store-type=JKS
server.ssl.key-alias=tomcat

zuul.routes.route-service.url=https://localhost:38443/route-management-service
zuul.routes.route-service.path=/route-management-service/routes/**

zuul.routes.navigator-service.url=https://localhost:38090
zuul.routes.navigator-service.path=/navigator/**
zuul.routes.navigator-service.stripPrefix=false

NAVIGATOR-SERVICE-SPRING.ribbon.ServerListRefreshInterval=5000

# ?????????? ??????, ????????? OOM
netflix.metrics.servo.enabled=false

# ??????????? ???? ??????? Tomcat
server.tomcat.max-threads=10
server.tomcat.min-spare-threads=2
