server.port=38081

server.ssl.enabled=true
server.ssl.key-store=file:/home/studs/s367527/services/zuul-proxy-dir/server.jks
server.ssl.key-store-password=changeit
server.ssl.key-store-type=JKS
server.ssl.key-alias=tomcat

eureka.client.serviceUrl.defaultZone=https://localhost:38080/eureka

zuul.routes.navigator-service.url=https://localhost:38090
zuul.routes.navigator-service.path=/navigator/**
zuul.routes.navigator-service.stripPrefix=false

zuul.sslHostnameValidationEnabled=false
zuul.host.connect-timeout-millis=5000
zuul.host.socket-timeout-millis=5000
zuul.host.ssl-negotiation-timeout=5000
ribbon.IsSecure=true
ribbon.TrustAll=true

NAVIGATOR-SERVICE-SPRING.ribbon.ServerListRefreshInterval=5000

netflix.metrics.servo.enabled=false

server.tomcat.max-threads=10
server.tomcat.min-spare-threads=2
